### ISSUE TITLE
platform_binary doesn't compile when bzlmod is enabled

### ISSUE THREAD

**Issue by linzhp** [uber/hermetic_cc_toolchain#20] opened 2023-03-21 04:00 UTC
Repro steps:

1. checkout #19 
2. `bazel build --enable_bzlmod //test/c:which_libc_linux_amd64_gnu.2.19`. The error I got was:

```
INFO: Invocation ID: 80d9d5f7-1492-4055-9f8c-2c055d08999f
WARNING: For repository 'com_google_protobuf', the root module requires module version protobuf@3.19.0, but got protobuf@3.19.6 in the resolved dependency graph.
INFO: Analyzed target //test/c:which_libc_linux_amd64_gnu.2.19 (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /home/user/go-repos/src/github.com/uber/bazel-zig-cc/test/c/BUILD:3:10: Compiling test/c/main.c failed: I/O exception during sandboxed execution: /home/user/.cache/bazel/_bazel_zplin/e65fef30a00cec4e8b16328a7a002d7c/sandbox/processwrapper-sandbox/105/execroot/_main/external (No such file or directory)
Target //test/c:which_libc_linux_amd64_gnu.2.19 failed to build
INFO: Elapsed time: 0.328s, Critical Path: 0.02s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully
```

**Comment by motiejus** [comment] 2023-03-21 07:51
Cannot reproduce on x86_64-linux:

```
 bazel build --enable_bzlmod //test/c:which_libc_linux_amd64_gnu.2.19
Starting local Bazel server and connecting to it...
DEBUG: gazelle@0.27.0/MODULE.bazel:7:6: WARNING: The bazel_gazelle Bazel module is still highly experimental and subject to change at any time. Only use it to try out bzlmod for now.
DEBUG: rules_go@0.37.0/MODULE.bazel:8:6: WARNING: The rules_go Bazel module is still highly experimental and subject to change at any time. Only use it to try out bzlmod for now.
DEBUG: rules_go@0.33.0/MODULE.bazel:7:6: WARNING: The rules_go Bazel module is still highly experimental and subject to change at any time. Only use it to try out bzlmod for now.
WARNING: For repository 'com_google_protobuf', the root module requires module version protobuf@3.19.0, but got protobuf@3.19.6 in the resolved dependency graph.
INFO: Analyzed target //test/c:which_libc_linux_amd64_gnu.2.19 (75 packages loaded, 4225 targets configured).
INFO: Found 1 target...
INFO: Deleting stale sandbox base /home/motiejus/.cache/bazel/_bazel_motiejus/6ec14a6813f13f2c8f1d8cce5637da2e/sandbox
Target //test/c:which_libc_linux_amd64_gnu.2.19 up-to-date:
  bazel-bin/test/c/which_libc_/libc_aware/platform:linux_amd64_gnu.2.19
INFO: Elapsed time: 80.088s, Critical Path: 32.17s
INFO: 7 processes: 5 internal, 2 linux-sandbox.
INFO: Build completed successfully, 7 total actions
motiejus@mtwork:/code/bazel-zig-cc$ 
```

**Comment by motiejus** [comment] 2023-04-24 09:14
cc @linzhp I merged the bzlMod changes. Can you check if the issue still persists and update the ticket or close it?

**Closed** 2023-04-24 14:53 UTC
